<?xml version="1.0" encoding="utf-8"?>
<Database Name="mcs_fs" Class="MCSAuthDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.4.1.16;Initial Catalog=mcs_fs;Persist Security Info=True;User ID=mcs_it" SettingsObjectName="ExternalModules.Properties.Settings" SettingsPropertyName="mcs_fsConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.user_info" Member="UserItems">
    <Type Name="UserItem">
      <Column Name="user_id" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="user_pwd" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="user_fullname" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="user_phone" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="user_fax" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="user_email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="cust_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vendor_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vndr_sub_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="team_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="session_id" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="lst_session_activity" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lst_login_dt" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="user_domain" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="is_active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="pwd_1" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="pwd_2" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="pwd_3" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="pwd_create_dt" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="is_attorney" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="conversion_deactivate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ExtFeedSavePath" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="old_session_id" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="ExtFeedMailServer" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ExtFeedMailBidFromAddr" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="ExtFeedMailInvFromAddr" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="msg_contact_insp" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="msg_contact_pmp" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="msg_contact_ldft" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="VendorItem_UserItem" Member="VendorItem" ThisKey="vendor_id" OtherKey="vendor_id" Type="VendorItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vendors" Member="VendorItems">
    <Type Name="VendorItem">
      <Column Name="vendor_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="vendor_num" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="adr1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="adr2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="state" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="zip" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="zip_sub" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="ph_num" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="mobile_num" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fax_num" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="email_addr" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="contact_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="max_num_insp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_domain" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="last_mod_user_id" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="last_mod_dt" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="wo_discount_percent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sub_cntr" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="parent_vendor_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="is_active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_rec_modified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="deact_for_conv" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="VendorItem_UserItem" Member="UserItems" ThisKey="vendor_id" OtherKey="vendor_id" Type="UserItem" />
    </Type>
  </Table>
</Database>