#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalModules.DBAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mcs_fs")]
	public partial class MCSAuthDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUserItem(UserItem instance);
    partial void UpdateUserItem(UserItem instance);
    partial void DeleteUserItem(UserItem instance);
    partial void InsertVendorItem(VendorItem instance);
    partial void UpdateVendorItem(VendorItem instance);
    partial void DeleteVendorItem(VendorItem instance);
    #endregion
		
		public MCSAuthDataContext() : 
				base(global::ExternalModules.Properties.Settings.Default.mcs_fsConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public MCSAuthDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MCSAuthDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MCSAuthDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MCSAuthDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UserItem> UserItems
		{
			get
			{
				return this.GetTable<UserItem>();
			}
		}
		
		public System.Data.Linq.Table<VendorItem> VendorItems
		{
			get
			{
				return this.GetTable<VendorItem>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_info")]
	public partial class UserItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _user_id;
		
		private string _user_name;
		
		private string _user_pwd;
		
		private string _user_fullname;
		
		private string _user_phone;
		
		private string _user_fax;
		
		private string _user_email;
		
		private System.Nullable<int> _cust_id;
		
		private System.Nullable<int> _vendor_id;
		
		private System.Nullable<long> _vndr_sub_id;
		
		private System.Nullable<int> _team_id;
		
		private int _user_type_id;
		
		private string _session_id;
		
		private System.Nullable<System.DateTime> _lst_session_activity;
		
		private System.Nullable<System.DateTime> _lst_login_dt;
		
		private string _user_domain;
		
		private bool _is_active;
		
		private string _pwd_1;
		
		private string _pwd_2;
		
		private string _pwd_3;
		
		private System.DateTime _pwd_create_dt;
		
		private System.Nullable<bool> _is_attorney;
		
		private System.Nullable<bool> _conversion_deactivate;
		
		private string _ExtFeedSavePath;
		
		private string _old_session_id;
		
		private string _ExtFeedMailServer;
		
		private string _ExtFeedMailBidFromAddr;
		
		private string _ExtFeedMailInvFromAddr;
		
		private System.Nullable<bool> _msg_contact_insp;
		
		private System.Nullable<bool> _msg_contact_pmp;
		
		private System.Nullable<bool> _msg_contact_ldft;
		
		private EntityRef<VendorItem> _VendorItem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(string value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onuser_pwdChanging(string value);
    partial void Onuser_pwdChanged();
    partial void Onuser_fullnameChanging(string value);
    partial void Onuser_fullnameChanged();
    partial void Onuser_phoneChanging(string value);
    partial void Onuser_phoneChanged();
    partial void Onuser_faxChanging(string value);
    partial void Onuser_faxChanged();
    partial void Onuser_emailChanging(string value);
    partial void Onuser_emailChanged();
    partial void Oncust_idChanging(System.Nullable<int> value);
    partial void Oncust_idChanged();
    partial void Onvendor_idChanging(System.Nullable<int> value);
    partial void Onvendor_idChanged();
    partial void Onvndr_sub_idChanging(System.Nullable<long> value);
    partial void Onvndr_sub_idChanged();
    partial void Onteam_idChanging(System.Nullable<int> value);
    partial void Onteam_idChanged();
    partial void Onuser_type_idChanging(int value);
    partial void Onuser_type_idChanged();
    partial void Onsession_idChanging(string value);
    partial void Onsession_idChanged();
    partial void Onlst_session_activityChanging(System.Nullable<System.DateTime> value);
    partial void Onlst_session_activityChanged();
    partial void Onlst_login_dtChanging(System.Nullable<System.DateTime> value);
    partial void Onlst_login_dtChanged();
    partial void Onuser_domainChanging(string value);
    partial void Onuser_domainChanged();
    partial void Onis_activeChanging(bool value);
    partial void Onis_activeChanged();
    partial void Onpwd_1Changing(string value);
    partial void Onpwd_1Changed();
    partial void Onpwd_2Changing(string value);
    partial void Onpwd_2Changed();
    partial void Onpwd_3Changing(string value);
    partial void Onpwd_3Changed();
    partial void Onpwd_create_dtChanging(System.DateTime value);
    partial void Onpwd_create_dtChanged();
    partial void Onis_attorneyChanging(System.Nullable<bool> value);
    partial void Onis_attorneyChanged();
    partial void Onconversion_deactivateChanging(System.Nullable<bool> value);
    partial void Onconversion_deactivateChanged();
    partial void OnExtFeedSavePathChanging(string value);
    partial void OnExtFeedSavePathChanged();
    partial void Onold_session_idChanging(string value);
    partial void Onold_session_idChanged();
    partial void OnExtFeedMailServerChanging(string value);
    partial void OnExtFeedMailServerChanged();
    partial void OnExtFeedMailBidFromAddrChanging(string value);
    partial void OnExtFeedMailBidFromAddrChanged();
    partial void OnExtFeedMailInvFromAddrChanging(string value);
    partial void OnExtFeedMailInvFromAddrChanged();
    partial void Onmsg_contact_inspChanging(System.Nullable<bool> value);
    partial void Onmsg_contact_inspChanged();
    partial void Onmsg_contact_pmpChanging(System.Nullable<bool> value);
    partial void Onmsg_contact_pmpChanged();
    partial void Onmsg_contact_ldftChanging(System.Nullable<bool> value);
    partial void Onmsg_contact_ldftChanged();
    #endregion
		
		public UserItem()
		{
			this._VendorItem = default(EntityRef<VendorItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="VarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_pwd", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string user_pwd
		{
			get
			{
				return this._user_pwd;
			}
			set
			{
				if ((this._user_pwd != value))
				{
					this.Onuser_pwdChanging(value);
					this.SendPropertyChanging();
					this._user_pwd = value;
					this.SendPropertyChanged("user_pwd");
					this.Onuser_pwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_fullname", DbType="VarChar(255)")]
		public string user_fullname
		{
			get
			{
				return this._user_fullname;
			}
			set
			{
				if ((this._user_fullname != value))
				{
					this.Onuser_fullnameChanging(value);
					this.SendPropertyChanging();
					this._user_fullname = value;
					this.SendPropertyChanged("user_fullname");
					this.Onuser_fullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_phone", DbType="VarChar(30)")]
		public string user_phone
		{
			get
			{
				return this._user_phone;
			}
			set
			{
				if ((this._user_phone != value))
				{
					this.Onuser_phoneChanging(value);
					this.SendPropertyChanging();
					this._user_phone = value;
					this.SendPropertyChanged("user_phone");
					this.Onuser_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_fax", DbType="VarChar(30)")]
		public string user_fax
		{
			get
			{
				return this._user_fax;
			}
			set
			{
				if ((this._user_fax != value))
				{
					this.Onuser_faxChanging(value);
					this.SendPropertyChanging();
					this._user_fax = value;
					this.SendPropertyChanged("user_fax");
					this.Onuser_faxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_email", DbType="VarChar(255)")]
		public string user_email
		{
			get
			{
				return this._user_email;
			}
			set
			{
				if ((this._user_email != value))
				{
					this.Onuser_emailChanging(value);
					this.SendPropertyChanging();
					this._user_email = value;
					this.SendPropertyChanged("user_email");
					this.Onuser_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_id", DbType="Int")]
		public System.Nullable<int> cust_id
		{
			get
			{
				return this._cust_id;
			}
			set
			{
				if ((this._cust_id != value))
				{
					this.Oncust_idChanging(value);
					this.SendPropertyChanging();
					this._cust_id = value;
					this.SendPropertyChanged("cust_id");
					this.Oncust_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendor_id", DbType="Int")]
		public System.Nullable<int> vendor_id
		{
			get
			{
				return this._vendor_id;
			}
			set
			{
				if ((this._vendor_id != value))
				{
					if (this._VendorItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onvendor_idChanging(value);
					this.SendPropertyChanging();
					this._vendor_id = value;
					this.SendPropertyChanged("vendor_id");
					this.Onvendor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vndr_sub_id", DbType="BigInt")]
		public System.Nullable<long> vndr_sub_id
		{
			get
			{
				return this._vndr_sub_id;
			}
			set
			{
				if ((this._vndr_sub_id != value))
				{
					this.Onvndr_sub_idChanging(value);
					this.SendPropertyChanging();
					this._vndr_sub_id = value;
					this.SendPropertyChanged("vndr_sub_id");
					this.Onvndr_sub_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_team_id", DbType="Int")]
		public System.Nullable<int> team_id
		{
			get
			{
				return this._team_id;
			}
			set
			{
				if ((this._team_id != value))
				{
					this.Onteam_idChanging(value);
					this.SendPropertyChanging();
					this._team_id = value;
					this.SendPropertyChanged("team_id");
					this.Onteam_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_type_id", DbType="Int NOT NULL")]
		public int user_type_id
		{
			get
			{
				return this._user_type_id;
			}
			set
			{
				if ((this._user_type_id != value))
				{
					this.Onuser_type_idChanging(value);
					this.SendPropertyChanging();
					this._user_type_id = value;
					this.SendPropertyChanged("user_type_id");
					this.Onuser_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_session_id", DbType="VarChar(36)")]
		public string session_id
		{
			get
			{
				return this._session_id;
			}
			set
			{
				if ((this._session_id != value))
				{
					this.Onsession_idChanging(value);
					this.SendPropertyChanging();
					this._session_id = value;
					this.SendPropertyChanged("session_id");
					this.Onsession_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lst_session_activity", DbType="DateTime")]
		public System.Nullable<System.DateTime> lst_session_activity
		{
			get
			{
				return this._lst_session_activity;
			}
			set
			{
				if ((this._lst_session_activity != value))
				{
					this.Onlst_session_activityChanging(value);
					this.SendPropertyChanging();
					this._lst_session_activity = value;
					this.SendPropertyChanged("lst_session_activity");
					this.Onlst_session_activityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lst_login_dt", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> lst_login_dt
		{
			get
			{
				return this._lst_login_dt;
			}
			set
			{
				if ((this._lst_login_dt != value))
				{
					this.Onlst_login_dtChanging(value);
					this.SendPropertyChanging();
					this._lst_login_dt = value;
					this.SendPropertyChanged("lst_login_dt");
					this.Onlst_login_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_domain", DbType="VarChar(36) NOT NULL", CanBeNull=false)]
		public string user_domain
		{
			get
			{
				return this._user_domain;
			}
			set
			{
				if ((this._user_domain != value))
				{
					this.Onuser_domainChanging(value);
					this.SendPropertyChanging();
					this._user_domain = value;
					this.SendPropertyChanged("user_domain");
					this.Onuser_domainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_active", DbType="Bit NOT NULL")]
		public bool is_active
		{
			get
			{
				return this._is_active;
			}
			set
			{
				if ((this._is_active != value))
				{
					this.Onis_activeChanging(value);
					this.SendPropertyChanging();
					this._is_active = value;
					this.SendPropertyChanged("is_active");
					this.Onis_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd_1", DbType="VarChar(30)")]
		public string pwd_1
		{
			get
			{
				return this._pwd_1;
			}
			set
			{
				if ((this._pwd_1 != value))
				{
					this.Onpwd_1Changing(value);
					this.SendPropertyChanging();
					this._pwd_1 = value;
					this.SendPropertyChanged("pwd_1");
					this.Onpwd_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd_2", DbType="VarChar(30)")]
		public string pwd_2
		{
			get
			{
				return this._pwd_2;
			}
			set
			{
				if ((this._pwd_2 != value))
				{
					this.Onpwd_2Changing(value);
					this.SendPropertyChanging();
					this._pwd_2 = value;
					this.SendPropertyChanged("pwd_2");
					this.Onpwd_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd_3", DbType="VarChar(30)")]
		public string pwd_3
		{
			get
			{
				return this._pwd_3;
			}
			set
			{
				if ((this._pwd_3 != value))
				{
					this.Onpwd_3Changing(value);
					this.SendPropertyChanging();
					this._pwd_3 = value;
					this.SendPropertyChanged("pwd_3");
					this.Onpwd_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd_create_dt", DbType="SmallDateTime NOT NULL")]
		public System.DateTime pwd_create_dt
		{
			get
			{
				return this._pwd_create_dt;
			}
			set
			{
				if ((this._pwd_create_dt != value))
				{
					this.Onpwd_create_dtChanging(value);
					this.SendPropertyChanging();
					this._pwd_create_dt = value;
					this.SendPropertyChanged("pwd_create_dt");
					this.Onpwd_create_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_attorney", DbType="Bit")]
		public System.Nullable<bool> is_attorney
		{
			get
			{
				return this._is_attorney;
			}
			set
			{
				if ((this._is_attorney != value))
				{
					this.Onis_attorneyChanging(value);
					this.SendPropertyChanging();
					this._is_attorney = value;
					this.SendPropertyChanged("is_attorney");
					this.Onis_attorneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conversion_deactivate", DbType="Bit")]
		public System.Nullable<bool> conversion_deactivate
		{
			get
			{
				return this._conversion_deactivate;
			}
			set
			{
				if ((this._conversion_deactivate != value))
				{
					this.Onconversion_deactivateChanging(value);
					this.SendPropertyChanging();
					this._conversion_deactivate = value;
					this.SendPropertyChanged("conversion_deactivate");
					this.Onconversion_deactivateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtFeedSavePath", DbType="VarChar(2000)")]
		public string ExtFeedSavePath
		{
			get
			{
				return this._ExtFeedSavePath;
			}
			set
			{
				if ((this._ExtFeedSavePath != value))
				{
					this.OnExtFeedSavePathChanging(value);
					this.SendPropertyChanging();
					this._ExtFeedSavePath = value;
					this.SendPropertyChanged("ExtFeedSavePath");
					this.OnExtFeedSavePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_old_session_id", DbType="VarChar(36)")]
		public string old_session_id
		{
			get
			{
				return this._old_session_id;
			}
			set
			{
				if ((this._old_session_id != value))
				{
					this.Onold_session_idChanging(value);
					this.SendPropertyChanging();
					this._old_session_id = value;
					this.SendPropertyChanged("old_session_id");
					this.Onold_session_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtFeedMailServer", DbType="VarChar(100)")]
		public string ExtFeedMailServer
		{
			get
			{
				return this._ExtFeedMailServer;
			}
			set
			{
				if ((this._ExtFeedMailServer != value))
				{
					this.OnExtFeedMailServerChanging(value);
					this.SendPropertyChanging();
					this._ExtFeedMailServer = value;
					this.SendPropertyChanged("ExtFeedMailServer");
					this.OnExtFeedMailServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtFeedMailBidFromAddr", DbType="VarChar(250)")]
		public string ExtFeedMailBidFromAddr
		{
			get
			{
				return this._ExtFeedMailBidFromAddr;
			}
			set
			{
				if ((this._ExtFeedMailBidFromAddr != value))
				{
					this.OnExtFeedMailBidFromAddrChanging(value);
					this.SendPropertyChanging();
					this._ExtFeedMailBidFromAddr = value;
					this.SendPropertyChanged("ExtFeedMailBidFromAddr");
					this.OnExtFeedMailBidFromAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtFeedMailInvFromAddr", DbType="VarChar(250)")]
		public string ExtFeedMailInvFromAddr
		{
			get
			{
				return this._ExtFeedMailInvFromAddr;
			}
			set
			{
				if ((this._ExtFeedMailInvFromAddr != value))
				{
					this.OnExtFeedMailInvFromAddrChanging(value);
					this.SendPropertyChanging();
					this._ExtFeedMailInvFromAddr = value;
					this.SendPropertyChanged("ExtFeedMailInvFromAddr");
					this.OnExtFeedMailInvFromAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msg_contact_insp", DbType="Bit")]
		public System.Nullable<bool> msg_contact_insp
		{
			get
			{
				return this._msg_contact_insp;
			}
			set
			{
				if ((this._msg_contact_insp != value))
				{
					this.Onmsg_contact_inspChanging(value);
					this.SendPropertyChanging();
					this._msg_contact_insp = value;
					this.SendPropertyChanged("msg_contact_insp");
					this.Onmsg_contact_inspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msg_contact_pmp", DbType="Bit")]
		public System.Nullable<bool> msg_contact_pmp
		{
			get
			{
				return this._msg_contact_pmp;
			}
			set
			{
				if ((this._msg_contact_pmp != value))
				{
					this.Onmsg_contact_pmpChanging(value);
					this.SendPropertyChanging();
					this._msg_contact_pmp = value;
					this.SendPropertyChanged("msg_contact_pmp");
					this.Onmsg_contact_pmpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msg_contact_ldft", DbType="Bit")]
		public System.Nullable<bool> msg_contact_ldft
		{
			get
			{
				return this._msg_contact_ldft;
			}
			set
			{
				if ((this._msg_contact_ldft != value))
				{
					this.Onmsg_contact_ldftChanging(value);
					this.SendPropertyChanging();
					this._msg_contact_ldft = value;
					this.SendPropertyChanged("msg_contact_ldft");
					this.Onmsg_contact_ldftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VendorItem_UserItem", Storage="_VendorItem", ThisKey="vendor_id", OtherKey="vendor_id", IsForeignKey=true)]
		public VendorItem VendorItem
		{
			get
			{
				return this._VendorItem.Entity;
			}
			set
			{
				VendorItem previousValue = this._VendorItem.Entity;
				if (((previousValue != value) 
							|| (this._VendorItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VendorItem.Entity = null;
						previousValue.UserItems.Remove(this);
					}
					this._VendorItem.Entity = value;
					if ((value != null))
					{
						value.UserItems.Add(this);
						this._vendor_id = value.vendor_id;
					}
					else
					{
						this._vendor_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("VendorItem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vendors")]
	public partial class VendorItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _vendor_id;
		
		private string _vendor_num;
		
		private string _name;
		
		private string _adr1;
		
		private string _adr2;
		
		private string _city;
		
		private string _state;
		
		private string _zip;
		
		private string _zip_sub;
		
		private string _ph_num;
		
		private string _mobile_num;
		
		private string _fax_num;
		
		private string _email_addr;
		
		private string _contact_name;
		
		private System.Nullable<int> _max_num_insp;
		
		private string _user_domain;
		
		private string _last_mod_user_id;
		
		private System.DateTime _last_mod_dt;
		
		private int _wo_discount_percent;
		
		private System.Nullable<bool> _sub_cntr;
		
		private System.Nullable<int> _parent_vendor_id;
		
		private bool _is_active;
		
		private System.Nullable<bool> _is_rec_modified;
		
		private System.Nullable<bool> _deact_for_conv;
		
		private EntitySet<UserItem> _UserItems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onvendor_idChanging(int value);
    partial void Onvendor_idChanged();
    partial void Onvendor_numChanging(string value);
    partial void Onvendor_numChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onadr1Changing(string value);
    partial void Onadr1Changed();
    partial void Onadr2Changing(string value);
    partial void Onadr2Changed();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OnzipChanging(string value);
    partial void OnzipChanged();
    partial void Onzip_subChanging(string value);
    partial void Onzip_subChanged();
    partial void Onph_numChanging(string value);
    partial void Onph_numChanged();
    partial void Onmobile_numChanging(string value);
    partial void Onmobile_numChanged();
    partial void Onfax_numChanging(string value);
    partial void Onfax_numChanged();
    partial void Onemail_addrChanging(string value);
    partial void Onemail_addrChanged();
    partial void Oncontact_nameChanging(string value);
    partial void Oncontact_nameChanged();
    partial void Onmax_num_inspChanging(System.Nullable<int> value);
    partial void Onmax_num_inspChanged();
    partial void Onuser_domainChanging(string value);
    partial void Onuser_domainChanged();
    partial void Onlast_mod_user_idChanging(string value);
    partial void Onlast_mod_user_idChanged();
    partial void Onlast_mod_dtChanging(System.DateTime value);
    partial void Onlast_mod_dtChanged();
    partial void Onwo_discount_percentChanging(int value);
    partial void Onwo_discount_percentChanged();
    partial void Onsub_cntrChanging(System.Nullable<bool> value);
    partial void Onsub_cntrChanged();
    partial void Onparent_vendor_idChanging(System.Nullable<int> value);
    partial void Onparent_vendor_idChanged();
    partial void Onis_activeChanging(bool value);
    partial void Onis_activeChanged();
    partial void Onis_rec_modifiedChanging(System.Nullable<bool> value);
    partial void Onis_rec_modifiedChanged();
    partial void Ondeact_for_convChanging(System.Nullable<bool> value);
    partial void Ondeact_for_convChanged();
    #endregion
		
		public VendorItem()
		{
			this._UserItems = new EntitySet<UserItem>(new Action<UserItem>(this.attach_UserItems), new Action<UserItem>(this.detach_UserItems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendor_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int vendor_id
		{
			get
			{
				return this._vendor_id;
			}
			set
			{
				if ((this._vendor_id != value))
				{
					this.Onvendor_idChanging(value);
					this.SendPropertyChanging();
					this._vendor_id = value;
					this.SendPropertyChanged("vendor_id");
					this.Onvendor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendor_num", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string vendor_num
		{
			get
			{
				return this._vendor_num;
			}
			set
			{
				if ((this._vendor_num != value))
				{
					this.Onvendor_numChanging(value);
					this.SendPropertyChanging();
					this._vendor_num = value;
					this.SendPropertyChanged("vendor_num");
					this.Onvendor_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adr1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string adr1
		{
			get
			{
				return this._adr1;
			}
			set
			{
				if ((this._adr1 != value))
				{
					this.Onadr1Changing(value);
					this.SendPropertyChanging();
					this._adr1 = value;
					this.SendPropertyChanged("adr1");
					this.Onadr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adr2", DbType="VarChar(50)")]
		public string adr2
		{
			get
			{
				return this._adr2;
			}
			set
			{
				if ((this._adr2 != value))
				{
					this.Onadr2Changing(value);
					this.SendPropertyChanging();
					this._adr2 = value;
					this.SendPropertyChanged("adr2");
					this.Onadr2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Char(2)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip", DbType="VarChar(5)")]
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				if ((this._zip != value))
				{
					this.OnzipChanging(value);
					this.SendPropertyChanging();
					this._zip = value;
					this.SendPropertyChanged("zip");
					this.OnzipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip_sub", DbType="VarChar(4)")]
		public string zip_sub
		{
			get
			{
				return this._zip_sub;
			}
			set
			{
				if ((this._zip_sub != value))
				{
					this.Onzip_subChanging(value);
					this.SendPropertyChanging();
					this._zip_sub = value;
					this.SendPropertyChanged("zip_sub");
					this.Onzip_subChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ph_num", DbType="VarChar(20)")]
		public string ph_num
		{
			get
			{
				return this._ph_num;
			}
			set
			{
				if ((this._ph_num != value))
				{
					this.Onph_numChanging(value);
					this.SendPropertyChanging();
					this._ph_num = value;
					this.SendPropertyChanged("ph_num");
					this.Onph_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile_num", DbType="VarChar(20)")]
		public string mobile_num
		{
			get
			{
				return this._mobile_num;
			}
			set
			{
				if ((this._mobile_num != value))
				{
					this.Onmobile_numChanging(value);
					this.SendPropertyChanging();
					this._mobile_num = value;
					this.SendPropertyChanged("mobile_num");
					this.Onmobile_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax_num", DbType="VarChar(20)")]
		public string fax_num
		{
			get
			{
				return this._fax_num;
			}
			set
			{
				if ((this._fax_num != value))
				{
					this.Onfax_numChanging(value);
					this.SendPropertyChanging();
					this._fax_num = value;
					this.SendPropertyChanged("fax_num");
					this.Onfax_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_addr", DbType="VarChar(250)")]
		public string email_addr
		{
			get
			{
				return this._email_addr;
			}
			set
			{
				if ((this._email_addr != value))
				{
					this.Onemail_addrChanging(value);
					this.SendPropertyChanging();
					this._email_addr = value;
					this.SendPropertyChanged("email_addr");
					this.Onemail_addrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_name", DbType="VarChar(50)")]
		public string contact_name
		{
			get
			{
				return this._contact_name;
			}
			set
			{
				if ((this._contact_name != value))
				{
					this.Oncontact_nameChanging(value);
					this.SendPropertyChanging();
					this._contact_name = value;
					this.SendPropertyChanged("contact_name");
					this.Oncontact_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_num_insp", DbType="Int")]
		public System.Nullable<int> max_num_insp
		{
			get
			{
				return this._max_num_insp;
			}
			set
			{
				if ((this._max_num_insp != value))
				{
					this.Onmax_num_inspChanging(value);
					this.SendPropertyChanging();
					this._max_num_insp = value;
					this.SendPropertyChanged("max_num_insp");
					this.Onmax_num_inspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_domain", DbType="VarChar(36) NOT NULL", CanBeNull=false)]
		public string user_domain
		{
			get
			{
				return this._user_domain;
			}
			set
			{
				if ((this._user_domain != value))
				{
					this.Onuser_domainChanging(value);
					this.SendPropertyChanging();
					this._user_domain = value;
					this.SendPropertyChanged("user_domain");
					this.Onuser_domainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_mod_user_id", DbType="VarChar(36) NOT NULL", CanBeNull=false)]
		public string last_mod_user_id
		{
			get
			{
				return this._last_mod_user_id;
			}
			set
			{
				if ((this._last_mod_user_id != value))
				{
					this.Onlast_mod_user_idChanging(value);
					this.SendPropertyChanging();
					this._last_mod_user_id = value;
					this.SendPropertyChanged("last_mod_user_id");
					this.Onlast_mod_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_mod_dt", DbType="SmallDateTime NOT NULL")]
		public System.DateTime last_mod_dt
		{
			get
			{
				return this._last_mod_dt;
			}
			set
			{
				if ((this._last_mod_dt != value))
				{
					this.Onlast_mod_dtChanging(value);
					this.SendPropertyChanging();
					this._last_mod_dt = value;
					this.SendPropertyChanged("last_mod_dt");
					this.Onlast_mod_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wo_discount_percent", DbType="Int NOT NULL")]
		public int wo_discount_percent
		{
			get
			{
				return this._wo_discount_percent;
			}
			set
			{
				if ((this._wo_discount_percent != value))
				{
					this.Onwo_discount_percentChanging(value);
					this.SendPropertyChanging();
					this._wo_discount_percent = value;
					this.SendPropertyChanged("wo_discount_percent");
					this.Onwo_discount_percentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub_cntr", DbType="Bit")]
		public System.Nullable<bool> sub_cntr
		{
			get
			{
				return this._sub_cntr;
			}
			set
			{
				if ((this._sub_cntr != value))
				{
					this.Onsub_cntrChanging(value);
					this.SendPropertyChanging();
					this._sub_cntr = value;
					this.SendPropertyChanged("sub_cntr");
					this.Onsub_cntrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_vendor_id", DbType="Int")]
		public System.Nullable<int> parent_vendor_id
		{
			get
			{
				return this._parent_vendor_id;
			}
			set
			{
				if ((this._parent_vendor_id != value))
				{
					this.Onparent_vendor_idChanging(value);
					this.SendPropertyChanging();
					this._parent_vendor_id = value;
					this.SendPropertyChanged("parent_vendor_id");
					this.Onparent_vendor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_active", DbType="Bit NOT NULL")]
		public bool is_active
		{
			get
			{
				return this._is_active;
			}
			set
			{
				if ((this._is_active != value))
				{
					this.Onis_activeChanging(value);
					this.SendPropertyChanging();
					this._is_active = value;
					this.SendPropertyChanged("is_active");
					this.Onis_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_rec_modified", DbType="Bit")]
		public System.Nullable<bool> is_rec_modified
		{
			get
			{
				return this._is_rec_modified;
			}
			set
			{
				if ((this._is_rec_modified != value))
				{
					this.Onis_rec_modifiedChanging(value);
					this.SendPropertyChanging();
					this._is_rec_modified = value;
					this.SendPropertyChanged("is_rec_modified");
					this.Onis_rec_modifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deact_for_conv", DbType="Bit")]
		public System.Nullable<bool> deact_for_conv
		{
			get
			{
				return this._deact_for_conv;
			}
			set
			{
				if ((this._deact_for_conv != value))
				{
					this.Ondeact_for_convChanging(value);
					this.SendPropertyChanging();
					this._deact_for_conv = value;
					this.SendPropertyChanged("deact_for_conv");
					this.Ondeact_for_convChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VendorItem_UserItem", Storage="_UserItems", ThisKey="vendor_id", OtherKey="vendor_id")]
		public EntitySet<UserItem> UserItems
		{
			get
			{
				return this._UserItems;
			}
			set
			{
				this._UserItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UserItems(UserItem entity)
		{
			this.SendPropertyChanging();
			entity.VendorItem = this;
		}
		
		private void detach_UserItems(UserItem entity)
		{
			this.SendPropertyChanging();
			entity.VendorItem = null;
		}
	}
}
#pragma warning restore 1591
