USE [master]
GO
/****** Object:  Database [IMDB]    Script Date: 11/26/2010 01:57:38 ******/
CREATE DATABASE [IMDB] ON  PRIMARY 
( NAME = N'IMDB', FILENAME = N'C:\Source\SQL\MSSQL\IMDB.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'IMDB_log', FILENAME = N'C:\Source\SQL\MSSQL\IMDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [IMDB] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IMDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [IMDB] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [IMDB] SET ANSI_NULLS OFF
GO
ALTER DATABASE [IMDB] SET ANSI_PADDING OFF
GO
ALTER DATABASE [IMDB] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [IMDB] SET ARITHABORT OFF
GO
ALTER DATABASE [IMDB] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [IMDB] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [IMDB] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [IMDB] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [IMDB] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [IMDB] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [IMDB] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [IMDB] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [IMDB] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [IMDB] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [IMDB] SET  DISABLE_BROKER
GO
ALTER DATABASE [IMDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [IMDB] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [IMDB] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [IMDB] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [IMDB] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [IMDB] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [IMDB] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [IMDB] SET  READ_WRITE
GO
ALTER DATABASE [IMDB] SET RECOVERY SIMPLE
GO
ALTER DATABASE [IMDB] SET  MULTI_USER
GO
ALTER DATABASE [IMDB] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [IMDB] SET DB_CHAINING OFF
GO
USE [IMDB]
GO
/****** Object:  Table [dbo].[tblMissedConversations]    Script Date: 11/26/2010 01:57:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tblMissedConversations](
	[MissedMessageID] [bigint] IDENTITY(1,1) NOT NULL,
	[UserID] [varchar](36) NOT NULL,
	[ConversatioID] [bigint] NOT NULL,
 CONSTRAINT [PK_tblMissedConversations] PRIMARY KEY CLUSTERED 
(
	[MissedMessageID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tblMessages]    Script Date: 11/26/2010 01:57:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblMessages](
	[MessageID] [bigint] IDENTITY(1,1) NOT NULL,
	[ConversationID] [bigint] NOT NULL,
	[MessageData] [image] NOT NULL,
 CONSTRAINT [PK_tblMessages] PRIMARY KEY CLUSTERED 
(
	[MessageID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblLastKnownStates]    Script Date: 11/26/2010 01:57:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tblLastKnownStates](
	[StateID] [bigint] IDENTITY(1,1) NOT NULL,
	[UserID] [varchar](36) NOT NULL,
	[LastKnownState] [varchar](255) NOT NULL,
 CONSTRAINT [PK_tblLastKnownStates] PRIMARY KEY CLUSTERED 
(
	[StateID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tblFiles]    Script Date: 11/26/2010 01:57:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tblFiles](
	[FileItemID] [bigint] IDENTITY(1,1) NOT NULL,
	[FileID] [varchar](36) NOT NULL,
	[FileName] [varchar](255) NOT NULL,
	[UploadDate] [datetime] NOT NULL,
	[FileBytes] [image] NOT NULL,
	[FileHash] [varchar](255) NOT NULL,
 CONSTRAINT [PK_tblFiles] PRIMARY KEY CLUSTERED 
(
	[FileItemID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tblConversationMembers]    Script Date: 11/26/2010 01:57:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tblConversationMembers](
	[ConversationMemberID] [bigint] IDENTITY(1,1) NOT NULL,
	[ConversationID] [bigint] NOT NULL,
	[UserID] [varchar](36) NOT NULL,
 CONSTRAINT [PK_tblConversationMembers] PRIMARY KEY CLUSTERED 
(
	[ConversationMemberID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tblConversationList]    Script Date: 11/26/2010 01:57:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tblConversationList](
	[ConversationID] [bigint] IDENTITY(1,1) NOT NULL,
	[ConversationGUID] [varchar](36) NOT NULL,
	[DateCreated] [datetime] NOT NULL,
 CONSTRAINT [PK_tblConversationList] PRIMARY KEY CLUSTERED 
(
	[ConversationID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
